apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-logging
bases:
- ../../base/
resources:
- schbck-only-cluster-resources.yaml
- schbck-ns-others.yaml
- schbck-ns-platform.yaml
